### ISSUE TITLE
只有时间限制,但没有时间段限制

### ISSUE THREAD

**Issue by TGTang** [YXJ2018/SpringBoot-Vue-OnlineExam#39]
一般考试都是规定时间段,比如14:00-16:00.
那么就是14:00才能进入,16:00自动提交.
我就是想参考怎么实现的,可惜这里没有
话说作者现在知道怎么实现吗

**Comment by YXJ2018** [comment]
> 一般考试都是规定时间段,比如14:00-16:00.
> 那么就是14:00才能进入,16:00自动提交.
> 我就是想参考怎么实现的,可惜这里没有
> 话说作者现在知道怎么实现吗

给你提供个思路，获取当前时间的hours，然后再判断是否在规定的时间范围内就好了。
