### ISSUE TITLE
前端安装依赖报错

### ISSUE THREAD

**Issue by HeYiai02** [YXJ2018/SpringBoot-Vue-OnlineExam#60]
yarn install 报错内容:error D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\node-sass
Output:
Building: D:\Environmental\nodejs\node.exe D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\Environmental\\nodejs\\node.exe',
gyp verb cli   'D:\\git-boot\\g\\SpringBoot-Vue-OnlineExam\\exam\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.13.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\Environmental\anaconda3\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\Environmental\anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\Environmental\\nodejs\\node.exe" "D:\\git-boot\\g\\SpringBoot-Vue-OnlineExam\\exam\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\git-boot\g\SpringBoot-Vue-OnlineExam\exam\node_modules\node-sass
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v3.8.0

**Comment by YXJ2018** [comment]
> node-sass

这个是按照node-sass报错了，你可以用yarn安装依赖，或者看这里https://blog.csdn.net/ken_ding/article/details/85623092

**Comment by HeYiai02** [comment]
后面还会有个sass-loader的报错，要手动装低版本的sass-loader
npm uninstall sass-loader（卸载当前版本）
npm install sass-loader@7.0.3 --save-dev
